# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Little Eight
email: siasiasiayang@gmail.com
description: >
    I just wanna run.
baseurl: ""   # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: Sia_Yang
github_username:  Mengying Yang
gems: [jekyll-paginate]

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
theme: minima
paginate: 2
paginate_path: "/blog/page:num/"

author:
  name      : Mengying
  job       : Frontend Engineer
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  github    : https://github.com/MengyingYang
  twitter   : http://twitter.com/nandomoreirame
  facebook  : http://facebook.com/fernando.dev
  linkedin  : http://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

defaults:
  -
    scope:
      path: "posts" # an empty string here means all files in the project
    values:
      layout: "blog-default"


